<div id="home" class="m-3">
    <div class="form-row">
        <div class="form-group col-md-3">
            <div id="Painel de Inserção" class="card">
                <div class="card-header">
                    <h3>Registro de Hórarios</h3>
                </div>
                <div class="card-body">
                    <label for="horario_entrada">Horário Entrada</label>
                    <input type="time" class="form-control" name="horario_entrada" id="horario_entrada">
                    <label for="horario_saida">Horário Saída</label>
                    <input type="time" class="form-control" name="horario_saida" id="horario_saida">
                </div>
            </div>
        </div>

    </div>
</div>

