<div id="home" class="m-3">
    <div id="msg"></div>
    <div class="form-row">
        <div class="form-group col-md-3">
            <div id="Painel de Inserção" class="card">
                <div class="card-header">
                    <h3>Registro de Hórarios</h3>
                </div>
                <div class="card-body">
                    <label for="horario_entrada">Horário Entrada</label>
                    <input required type="datetime-local" class="form-control" name="horario_entrada" id="horario_entrada">
                    <label for="horario_saida">Horário Saída</label>
                    <input required type="datetime-local" class="form-control" name="horario_saida" id="horario_saida">
                </div>
                <button class="btn btn-primary" type="button" id="enviarHorario">Enviar</button>
            </div>
        </div>

        <div class="col-md-9">
            <div id="registro_hora" class="card">
                <div class="card-header">
                    <h3>
                        Registros
                    </h3>
                </div>
                    <div class="card-body" id="registros_unitarios">
                        <div class="row mb-2">
                            <div class="col-md-3"><b>Entrada </b></div>
                            <div class="col-md-3"><b>Saida </b></div>
                            <div class="col-md-2"><b> Tempo Total </b></div>
                            <div class="col-md-2"><b> Diurno </b></div>
                            <div class="col-md-2"><b> Noturno </b></div>
                        </div>
                    </div>

            </div>
        </div>
    </div>
</div>

